import https from 'node:https';
import fs from 'node:fs';
import path from 'node:path';

// BACKEND_URL — base URL of the mTLS management server (default: local dev)
const BACKEND_BASE = process.env.BACKEND_URL ?? 'https://127.0.0.1:8443';

// BACKEND_CERTS_DIR — directory containing operator.crt, operator.key, ca.crt
// These are generated by the backend on first run.
const CERTS_DIR =
	process.env.BACKEND_CERTS_DIR ?? '/home/matt/capstone/backend/certs';

function certs() {
	return {
		cert: fs.readFileSync(path.join(CERTS_DIR, 'operator.crt')),
		key: fs.readFileSync(path.join(CERTS_DIR, 'operator.key')),
		ca: fs.readFileSync(path.join(CERTS_DIR, 'ca.crt'))
	};
}

function request<T>(method: string, urlPath: string, body?: unknown): Promise<T> {
	return new Promise((resolve, reject) => {
		let certData: ReturnType<typeof certs>;
		try {
			certData = certs();
		} catch (e) {
			reject(new Error(`Could not load operator certs from ${CERTS_DIR}: ${e}`));
			return;
		}

		const url = new URL(urlPath, BACKEND_BASE);
		const payload = body !== undefined ? JSON.stringify(body) : undefined;

		const req = https.request(
			{
				hostname: url.hostname,
				port: Number(url.port) || 8443,
				path: url.pathname + url.search,
				method,
				cert: certData.cert,
				key: certData.key,
				ca: certData.ca,
				headers: {
					'Content-Type': 'application/json',
					...(payload ? { 'Content-Length': Buffer.byteLength(payload) } : {})
				}
			},
			(res) => {
				const chunks: Buffer[] = [];
				res.on('data', (chunk: Buffer) => chunks.push(chunk));
				res.on('end', () => {
					const text = Buffer.concat(chunks).toString();
					if ((res.statusCode ?? 0) >= 400) {
						reject(new Error(`Backend ${res.statusCode}: ${text}`));
						return;
					}
					try {
						resolve(JSON.parse(text) as T);
					} catch {
						resolve(text as unknown as T);
					}
				});
			}
		);

		req.on('error', reject);
		if (payload) req.write(payload);
		req.end();
	});
}

export interface Task {
	task_id: string;
	assigned_at: string;
	instruction: string;
	arg: string | null;
	exit_code: number | null;
	stdout: string;
	stderr: string;
	stopped_processing_at: string;
	responded: boolean;
	inventory: Record<string, unknown> | null;
}

export interface Agent {
	id: string;
	hostname: string;
	ip_address: string;
	os: string;
	os_name: string;
	registered_at: string;
	last_seen: string;
	blacklisted: boolean;
	cert_fingerprint?: string;
	tasks: Task[];
}

export interface CronConfig {
	inventory_interval: number;
	page_refresh_interval: number;
}

export const backend = {
	listAgents: () => request<Agent[]>('GET', '/api/man/agents'),
	getAgent: (id: string) => request<Agent>('GET', `/api/man/agents/${id}`),
	postTask: (agentid: string, task: Partial<Task>) =>
		request<{ status: string }>('POST', '/api/man/post_task', { agentid, task }),
	getCronConfig: () => request<CronConfig>('GET', '/api/man/cron'),
	patchCronConfig: (config: Partial<CronConfig>) =>
		request<CronConfig>('PATCH', '/api/man/cron', config)
};
